// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module edge_cnn_linear_conv_2d_cl_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer9_out_dout,
        layer9_out_empty_n,
        layer9_out_read,
        layer6_out_TDATA,
        layer6_out_TVALID,
        layer6_out_TREADY
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] layer9_out_dout;
input   layer9_out_empty_n;
output   layer9_out_read;
output  [63:0] layer6_out_TDATA;
output   layer6_out_TVALID;
input   layer6_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer9_out_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer9_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln85_fu_276_p2;
wire   [15:0] trunc_ln144_fu_288_p1;
reg   [15:0] trunc_ln144_reg_341;
reg   [15:0] trunc_ln144_s_reg_346;
reg   [15:0] trunc_ln144_5_reg_351;
reg   [15:0] trunc_ln144_6_reg_356;
wire    grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start;
wire    grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_done;
wire    grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_idle;
wire    grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_ready;
wire   [63:0] grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TDATA;
wire    grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TVALID;
wire    grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TREADY;
reg    grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start_reg;
reg    ap_block_state2_ignore_call8;
wire    ap_CS_fsm_state3;
reg   [14:0] indvar_flatten_fu_150;
wire   [14:0] add_ln85_fu_282_p2;
reg    ap_block_state2;
reg    ap_block_state1;
wire    ap_CS_fsm_state4;
wire    regslice_both_layer6_out_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    layer6_out_TREADY_int_regslice;
wire    regslice_both_layer6_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start_reg = 1'b0;
end

edge_cnn_linear_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_ready),
    .p_read(trunc_ln144_reg_341),
    .p_read1(trunc_ln144_s_reg_346),
    .p_read2(trunc_ln144_5_reg_351),
    .p_read3(trunc_ln144_6_reg_356),
    .layer6_out_TDATA(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TDATA),
    .layer6_out_TVALID(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TVALID),
    .layer6_out_TREADY(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TREADY)
);

edge_cnn_linear_regslice_both #(
    .DataWidth( 64 ))
regslice_both_layer6_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TDATA),
    .vld_in(grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TVALID),
    .ack_in(layer6_out_TREADY_int_regslice),
    .data_out(layer6_out_TDATA),
    .vld_out(regslice_both_layer6_out_U_vld_out),
    .ack_out(layer6_out_TREADY),
    .apdone_blk(regslice_both_layer6_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((regslice_both_layer6_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln85_fu_276_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln85_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_150 <= 15'd0;
    end else if ((~((icmp_ln85_fu_276_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln85_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_150 <= add_ln85_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln85_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln144_5_reg_351 <= {{layer9_out_dout[47:32]}};
        trunc_ln144_6_reg_356 <= {{layer9_out_dout[63:48]}};
        trunc_ln144_reg_341 <= trunc_ln144_fu_288_p1;
        trunc_ln144_s_reg_346 <= {{layer9_out_dout[31:16]}};
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_276_p2 == 1'd0) & (layer9_out_empty_n == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_layer6_out_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_layer6_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_layer6_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer9_out_blk_n = layer9_out_empty_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln85_fu_276_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln85_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer9_out_read = 1'b1;
    end else begin
        layer9_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln85_fu_276_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln85_fu_276_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((icmp_ln85_fu_276_p2 == 1'd0) & (layer9_out_empty_n == 1'b0)) & (icmp_ln85_fu_276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((regslice_both_layer6_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_fu_282_p2 = (indvar_flatten_fu_150 + 15'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln85_fu_276_p2 == 1'd0) & (layer9_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call8 = ((icmp_ln85_fu_276_p2 == 1'd0) & (layer9_out_empty_n == 1'b0));
end

assign grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start = grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_ap_start_reg;

assign grp_compute_output_buffer_2d_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s_fu_160_layer6_out_TREADY = (layer6_out_TREADY_int_regslice & ap_CS_fsm_state3);

assign icmp_ln85_fu_276_p2 = ((indvar_flatten_fu_150 == 15'd20172) ? 1'b1 : 1'b0);

assign layer6_out_TVALID = regslice_both_layer6_out_U_vld_out;

assign trunc_ln144_fu_288_p1 = layer9_out_dout[15:0];

endmodule //edge_cnn_linear_conv_2d_cl_array_ap_fixed_16_6_5_3_0_4u_array_ap_fixed_39_19_5_3_0_1u_config6_s
