-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    layer4_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    layer4_out_TVALID : OUT STD_LOGIC;
    layer4_out_TREADY : IN STD_LOGIC );
end;


architecture behav of myproject_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_A4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100100";
    constant ap_const_lv32_7B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal sX : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal layer4_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln284_reg_381 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_1_reg_395 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal and_ln284_1_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln303_reg_399 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln313_fu_358_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln307_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_done : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_idle : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_ready : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld : STD_LOGIC;
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_done : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_idle : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_ready : STD_LOGIC;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge_reg_111 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_op25_write_state3 : BOOLEAN;
    signal ap_block_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_predicate_op24_call_state3 : BOOLEAN;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg : STD_LOGIC := '0';
    signal select_ln318_fu_311_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln307_fu_336_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln303_fu_289_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_245_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_3_fu_261_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln284_4_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln284_5_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln318_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln313_fu_353_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_condition_183 : BOOLEAN;
    signal ap_condition_295 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_i : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld : OUT STD_LOGIC );
    end component;


    component myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122 : component myproject_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start,
        ap_done => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_done,
        ap_idle => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_idle,
        ap_ready => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_ready,
        p_read => p_read,
        p_read1 => p_read1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_i => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_i => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_i => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_i => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_i => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_i => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld => call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld);

    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174 : component myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start,
        ap_done => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_done,
        ap_idle => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_idle,
        ap_ready => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_ready,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig => void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7 => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6 => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3 => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2 => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1 => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a => p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a,
        ap_return => grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln284_fu_226_p2 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln284_1_fu_283_p2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_ready = ap_const_logic_1)) then 
                    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    pX_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_183)) then
                if ((icmp_ln303_fu_294_p2 = ap_const_lv1_1)) then 
                    pX <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_294_p2 = ap_const_lv1_0)) then 
                    pX <= add_ln303_fu_289_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_295)) then
                if ((icmp_ln307_fu_341_p2 = ap_const_lv1_1)) then 
                    pY <= ap_const_lv32_0;
                elsif ((icmp_ln307_fu_341_p2 = ap_const_lv1_0)) then 
                    pY <= add_ln307_fu_336_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_183)) then
                if ((icmp_ln303_fu_294_p2 = ap_const_lv1_1)) then 
                    sX <= ap_const_lv32_0;
                elsif ((icmp_ln303_fu_294_p2 = ap_const_lv1_0)) then 
                    sX <= select_ln318_fu_311_p3;
                end if;
            end if; 
        end if;
    end process;

    storemerge_reg_111_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_295)) then
                if ((icmp_ln307_fu_341_p2 = ap_const_lv1_1)) then 
                    storemerge_reg_111 <= ap_const_lv32_0;
                elsif ((icmp_ln307_fu_341_p2 = ap_const_lv1_0)) then 
                    storemerge_reg_111 <= select_ln313_fu_358_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln284_fu_226_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                and_ln284_1_reg_395 <= and_ln284_1_fu_283_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln284_reg_381 <= icmp_ln284_fu_226_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                icmp_ln303_reg_399 <= icmp_ln303_fu_294_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld = ap_const_logic_1))) then
                p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln303_reg_399 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                sY <= storemerge_reg_111;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld = ap_const_logic_1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, layer4_out_TREADY, ap_CS_fsm_state3, ap_predicate_op25_write_state3, ap_block_state3_io, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if ((not(((ap_const_boolean_1 = ap_block_state3_on_subcall_done) or (ap_const_boolean_1 = ap_block_state3_io) or ((layer4_out_TREADY = ap_const_logic_0) and (ap_predicate_op25_write_state3 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln303_fu_289_p2 <= std_logic_vector(unsigned(pX) + unsigned(ap_const_lv32_1));
    add_ln307_fu_336_p2 <= std_logic_vector(unsigned(pY) + unsigned(ap_const_lv32_1));
    add_ln313_fu_353_p2 <= std_logic_vector(unsigned(sY) + unsigned(ap_const_lv32_1));
    add_ln318_fu_306_p2 <= std_logic_vector(unsigned(sX) + unsigned(ap_const_lv32_1));
    and_ln284_1_fu_283_p2 <= (grp_fu_217_p2 and and_ln284_fu_277_p2);
    and_ln284_fu_277_p2 <= (icmp_ln284_5_fu_271_p2 and icmp_ln284_4_fu_255_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(layer4_out_TREADY, ap_predicate_op25_write_state3, ap_block_state3_io, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_boolean_1 = ap_block_state3_on_subcall_done) or (ap_const_boolean_1 = ap_block_state3_io) or ((layer4_out_TREADY = ap_const_logic_0) and (ap_predicate_op25_write_state3 = ap_const_boolean_1)))) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state3_assign_proc : process(layer4_out_TREADY, ap_predicate_op25_write_state3)
    begin
                ap_block_state3 <= ((layer4_out_TREADY = ap_const_logic_0) and (ap_predicate_op25_write_state3 = ap_const_boolean_1));
    end process;


    ap_block_state3_io_assign_proc : process(layer4_out_TREADY, ap_predicate_op25_write_state3)
    begin
                ap_block_state3_io <= ((layer4_out_TREADY = ap_const_logic_0) and (ap_predicate_op25_write_state3 = ap_const_boolean_1));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_done, ap_predicate_op24_call_state3)
    begin
                ap_block_state3_on_subcall_done <= ((ap_predicate_op24_call_state3 = ap_const_boolean_1) and (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_done = ap_const_logic_0));
    end process;


    ap_condition_183_assign_proc : process(layer4_out_TREADY, ap_CS_fsm_state3, ap_predicate_op25_write_state3, ap_block_state3_io, ap_block_state3_on_subcall_done)
    begin
                ap_condition_183 <= (not(((ap_const_boolean_1 = ap_block_state3_on_subcall_done) or (ap_const_boolean_1 = ap_block_state3_io) or ((layer4_out_TREADY = ap_const_logic_0) and (ap_predicate_op25_write_state3 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state3));
    end process;


    ap_condition_295_assign_proc : process(layer4_out_TREADY, ap_CS_fsm_state3, icmp_ln303_fu_294_p2, ap_predicate_op25_write_state3, ap_block_state3_io, ap_block_state3_on_subcall_done)
    begin
                ap_condition_295 <= (not(((ap_const_boolean_1 = ap_block_state3_on_subcall_done) or (ap_const_boolean_1 = ap_block_state3_io) or ((layer4_out_TREADY = ap_const_logic_0) and (ap_predicate_op25_write_state3 = ap_const_boolean_1)))) and (icmp_ln303_fu_294_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op24_call_state3_assign_proc : process(icmp_ln284_reg_381, and_ln284_1_reg_395)
    begin
                ap_predicate_op24_call_state3 <= ((ap_const_lv1_1 = and_ln284_1_reg_395) and (icmp_ln284_reg_381 = ap_const_lv1_1));
    end process;


    ap_predicate_op25_write_state3_assign_proc : process(icmp_ln284_reg_381, and_ln284_1_reg_395)
    begin
                ap_predicate_op25_write_state3 <= ((ap_const_lv1_1 = and_ln284_1_reg_395) and (icmp_ln284_reg_381 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start <= ap_const_logic_1;
        else 
            call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg;
    grp_fu_217_p2 <= "1" when (sY = ap_const_lv32_2) else "0";
    icmp_ln284_4_fu_255_p2 <= "1" when (signed(tmp_fu_245_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_5_fu_271_p2 <= "1" when (signed(tmp_3_fu_261_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_ln284_fu_226_p2 <= "1" when (sX = ap_const_lv32_2) else "0";
    icmp_ln303_fu_294_p2 <= "1" when (add_ln303_fu_289_p2 = ap_const_lv32_A4) else "0";
    icmp_ln307_fu_341_p2 <= "1" when (add_ln307_fu_336_p2 = ap_const_lv32_7B) else "0";
    layer4_out_TDATA <= grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_return;

    layer4_out_TDATA_blk_n_assign_proc : process(layer4_out_TREADY, ap_CS_fsm_state3, icmp_ln284_reg_381, and_ln284_1_reg_395)
    begin
        if (((ap_const_lv1_1 = and_ln284_1_reg_395) and (icmp_ln284_reg_381 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer4_out_TDATA_blk_n <= layer4_out_TREADY;
        else 
            layer4_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer4_out_TVALID_assign_proc : process(layer4_out_TREADY, ap_CS_fsm_state3, ap_predicate_op25_write_state3, ap_block_state3_io, ap_block_state3_on_subcall_done)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state3_on_subcall_done) or (ap_const_boolean_1 = ap_block_state3_io) or ((layer4_out_TREADY = ap_const_logic_0) and (ap_predicate_op25_write_state3 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_predicate_op25_write_state3 = ap_const_boolean_1))) then 
            layer4_out_TVALID <= ap_const_logic_1;
        else 
            layer4_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln313_fu_358_p3 <= 
        ap_const_lv32_2 when (grp_fu_217_p2(0) = '1') else 
        add_ln313_fu_353_p2;
    select_ln318_fu_311_p3 <= 
        ap_const_lv32_2 when (icmp_ln284_reg_381(0) = '1') else 
        add_ln318_fu_306_p2;
    tmp_3_fu_261_p4 <= pX(31 downto 1);
    tmp_fu_245_p4 <= pY(31 downto 1);
end behav;
