// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_ap_fixed_2u_array_ap_fixed_8_2_5_3_0_1u_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer6_out_dout,
        layer6_out_empty_n,
        layer6_out_read,
        layer4_out_TDATA,
        layer4_out_TVALID,
        layer4_out_TREADY
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] layer6_out_dout;
input   layer6_out_empty_n;
output   layer6_out_read;
output  [7:0] layer4_out_TDATA;
output   layer4_out_TVALID;
input   layer4_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer6_out_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer6_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln85_fu_178_p2;
wire   [7:0] trunc_ln144_fu_190_p1;
reg   [7:0] trunc_ln144_reg_221;
reg   [7:0] trunc_ln144_3_reg_226;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_ready;
wire   [7:0] grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TDATA;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TVALID;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TREADY;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start_reg;
reg    ap_block_state2_ignore_call6;
wire    ap_CS_fsm_state3;
reg   [14:0] indvar_flatten_fu_98;
wire   [14:0] add_ln85_fu_184_p2;
reg    ap_block_state2;
reg    ap_block_state1;
wire    ap_CS_fsm_state4;
wire    regslice_both_layer4_out_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    layer4_out_TREADY_int_regslice;
wire    regslice_both_layer4_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start_reg = 1'b0;
end

myproject_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_ready),
    .p_read(trunc_ln144_reg_221),
    .p_read1(trunc_ln144_3_reg_226),
    .layer4_out_TDATA(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TDATA),
    .layer4_out_TVALID(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TVALID),
    .layer4_out_TREADY(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TREADY)
);

myproject_regslice_both #(
    .DataWidth( 8 ))
regslice_both_layer4_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TDATA),
    .vld_in(grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TVALID),
    .ack_in(layer4_out_TREADY_int_regslice),
    .data_out(layer4_out_TDATA),
    .vld_out(regslice_both_layer4_out_U_vld_out),
    .ack_out(layer4_out_TREADY),
    .apdone_blk(regslice_both_layer4_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((regslice_both_layer4_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln85_fu_178_p2 == 1'd0) & (layer6_out_empty_n == 1'b0)) & (icmp_ln85_fu_178_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_98 <= 15'd0;
    end else if ((~((icmp_ln85_fu_178_p2 == 1'd0) & (layer6_out_empty_n == 1'b0)) & (icmp_ln85_fu_178_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_98 <= add_ln85_fu_184_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln85_fu_178_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln144_3_reg_226 <= {{layer6_out_dout[15:8]}};
        trunc_ln144_reg_221 <= trunc_ln144_fu_190_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_178_p2 == 1'd0) & (layer6_out_empty_n == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_layer4_out_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_layer4_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_layer4_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_178_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln85_fu_178_p2 == 1'd0) & (layer6_out_empty_n == 1'b0)) & (icmp_ln85_fu_178_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln85_fu_178_p2 == 1'd0) & (layer6_out_empty_n == 1'b0)) & (icmp_ln85_fu_178_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((icmp_ln85_fu_178_p2 == 1'd0) & (layer6_out_empty_n == 1'b0)) & (icmp_ln85_fu_178_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((regslice_both_layer4_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_fu_184_p2 = (indvar_flatten_fu_98 + 15'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln85_fu_178_p2 == 1'd0) & (layer6_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call6 = ((icmp_ln85_fu_178_p2 == 1'd0) & (layer6_out_empty_n == 1'b0));
end

assign grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_ap_start_reg;

assign grp_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s_fu_108_layer4_out_TREADY = (layer4_out_TREADY_int_regslice & ap_CS_fsm_state3);

assign icmp_ln85_fu_178_p2 = ((indvar_flatten_fu_98 == 15'd20172) ? 1'b1 : 1'b0);

assign layer4_out_TVALID = regslice_both_layer4_out_U_vld_out;

assign trunc_ln144_fu_190_p1 = layer6_out_dout[7:0];

endmodule //myproject_conv_2d_cl_array_ap_fixed_2u_array_ap_fixed_8_2_5_3_0_1u_config4_s
