-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_2_5_3_0_1u_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    input_image_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    input_image_TVALID : IN STD_LOGIC;
    input_image_TREADY : OUT STD_LOGIC;
    layer5_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    layer5_out_full_n : IN STD_LOGIC;
    layer5_out_write : OUT STD_LOGIC );
end;


architecture behav of myproject_zeropad2d_cl_array_ap_fixed_1u_array_ap_fixed_8_2_5_3_0_1u_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv7_79 : STD_LOGIC_VECTOR (6 downto 0) := "1111001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer5_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln59_fu_84_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_done : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_idle : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_ready : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_layer5_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_layer5_out_write : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_idle : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_ready : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_layer5_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_layer5_out_write : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_done : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_idle : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_ready : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_write : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_input_image_TREADY : STD_LOGIC;
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call4 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state4_ignore_call1 : BOOLEAN;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal i_fu_44 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln59_fu_90_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_state4 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal regslice_both_input_image_U_apdone_blk : STD_LOGIC;
    signal input_image_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal input_image_TVALID_int_regslice : STD_LOGIC;
    signal input_image_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_image_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer5_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        layer5_out_full_n : IN STD_LOGIC;
        layer5_out_write : OUT STD_LOGIC );
    end component;


    component myproject_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer5_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        layer5_out_full_n : IN STD_LOGIC;
        layer5_out_write : OUT STD_LOGIC );
    end component;


    component myproject_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer5_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        layer5_out_full_n : IN STD_LOGIC;
        layer5_out_write : OUT STD_LOGIC;
        input_image_TVALID : IN STD_LOGIC;
        input_image_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        input_image_TREADY : OUT STD_LOGIC );
    end component;


    component myproject_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56 : component myproject_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start,
        ap_done => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_done,
        ap_idle => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_idle,
        ap_ready => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_ready,
        layer5_out_din => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_layer5_out_din,
        layer5_out_full_n => layer5_out_full_n,
        layer5_out_write => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_layer5_out_write);

    grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62 : component myproject_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start,
        ap_done => grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done,
        ap_idle => grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_idle,
        ap_ready => grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_ready,
        layer5_out_din => grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_layer5_out_din,
        layer5_out_full_n => layer5_out_full_n,
        layer5_out_write => grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_layer5_out_write);

    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68 : component myproject_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start,
        ap_done => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_done,
        ap_idle => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_idle,
        ap_ready => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_ready,
        layer5_out_din => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_din,
        layer5_out_full_n => layer5_out_full_n,
        layer5_out_write => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_write,
        input_image_TVALID => input_image_TVALID_int_regslice,
        input_image_TDATA => input_image_TDATA_int_regslice,
        input_image_TREADY => grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_input_image_TREADY);

    regslice_both_input_image_U : component myproject_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_image_TDATA,
        vld_in => input_image_TVALID,
        ack_in => regslice_both_input_image_U_ack_in,
        data_out => input_image_TDATA_int_regslice,
        vld_out => input_image_TVALID_int_regslice,
        ack_out => input_image_TREADY_int_regslice,
        apdone_blk => regslice_both_input_image_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0))) and (icmp_ln59_fu_84_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_ready = ap_const_logic_1)) then 
                    grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_ready = ap_const_logic_1)) then 
                    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_44_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_44 <= ap_const_lv7_0;
            elsif ((not(((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0))) and (icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_fu_44 <= add_ln59_fu_90_p2;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, layer5_out_full_n, ap_CS_fsm_state4, icmp_ln59_fu_84_p2, grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_done, grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done, grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if ((not(((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0))) and (icmp_ln59_fu_84_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                elsif ((not(((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0))) and (icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln59_fu_90_p2 <= std_logic_vector(unsigned(i_fu_44) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_done)
    begin
        if ((grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(layer5_out_full_n, icmp_ln59_fu_84_p2)
    begin
        if (((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0))) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_done)
    begin
        if ((grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done)
    begin
        if ((grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call4_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call4 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(layer5_out_full_n, icmp_ln59_fu_84_p2)
    begin
                ap_block_state4 <= ((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_ignore_call1_assign_proc : process(layer5_out_full_n, icmp_ln59_fu_84_p2)
    begin
                ap_block_state4_ignore_call1 <= ((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done, ap_CS_fsm_state7)
    begin
        if (((grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start <= grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_start_reg;
    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start <= grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_ap_start_reg;
    grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start <= grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_ap_start_reg;
    icmp_ln59_fu_84_p2 <= "1" when (i_fu_44 = ap_const_lv7_79) else "0";
    input_image_TREADY <= regslice_both_input_image_U_ack_in;

    input_image_TREADY_int_regslice_assign_proc : process(grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_input_image_TREADY, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            input_image_TREADY_int_regslice <= grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_input_image_TREADY;
        else 
            input_image_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done, ap_CS_fsm_state7)
    begin
        if (((grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer5_out_blk_n_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state4, icmp_ln59_fu_84_p2)
    begin
        if (((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer5_out_blk_n <= layer5_out_full_n;
        else 
            layer5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer5_out_din_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state4, icmp_ln59_fu_84_p2, grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_layer5_out_din, grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_layer5_out_din, grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_din, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state6)
    begin
        if ((not(((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0))) and (icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer5_out_din <= ap_const_lv8_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            layer5_out_din <= grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            layer5_out_din <= grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_layer5_out_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer5_out_din <= grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_layer5_out_din;
        else 
            layer5_out_din <= grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_din;
        end if; 
    end process;


    layer5_out_write_assign_proc : process(layer5_out_full_n, ap_CS_fsm_state4, icmp_ln59_fu_84_p2, grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_layer5_out_write, grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_layer5_out_write, grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_write, ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state6)
    begin
        if ((not(((icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (layer5_out_full_n = ap_const_logic_0))) and (icmp_ln59_fu_84_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer5_out_write <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            layer5_out_write <= grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_CopyMain_fu_68_layer5_out_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            layer5_out_write <= grp_zeropad2d_cl_array_array_ap_fixed_1u_config5_Pipeline_PadBottomWidth_fu_62_layer5_out_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer5_out_write <= grp_zeropad2d_cl_array_array_ap_fixed_8_2_5_3_0_1u_config5_Pipeline_PadTopWidth_fu_56_layer5_out_write;
        else 
            layer5_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
