// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module edge_cnn_linear_relu_array_ap_fixed_37_17_5_3_0_4u_array_ap_fixed_16_6_5_3_0_4u_relu_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer2_out_dout,
        layer2_out_empty_n,
        layer2_out_read,
        layer3_out_din,
        layer3_out_full_n,
        layer3_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [147:0] layer2_out_dout;
input   layer2_out_empty_n;
output   layer2_out_read;
output  [63:0] layer3_out_din;
input   layer3_out_full_n;
output   layer3_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer2_out_read;
reg layer3_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_99_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer2_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer3_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] select_ln51_fu_166_p3;
reg   [15:0] select_ln51_reg_266;
wire   [15:0] select_ln51_4_fu_190_p3;
reg   [15:0] select_ln51_4_reg_271;
wire   [15:0] select_ln51_5_fu_214_p3;
reg   [15:0] select_ln51_5_reg_276;
wire   [15:0] select_ln51_6_fu_238_p3;
reg   [15:0] select_ln51_6_reg_281;
reg   [14:0] i_fu_74;
wire   [14:0] i_7_fu_105_p2;
wire    ap_loop_init;
reg   [14:0] ap_sig_allocacmp_i_6;
reg    ap_block_pp0_stage0_01001;
wire   [36:0] trunc_ln144_fu_116_p1;
wire   [0:0] icmp_ln1547_fu_150_p2;
wire   [15:0] trunc_ln2_fu_156_p4;
wire   [36:0] trunc_ln144_s_fu_120_p4;
wire   [0:0] icmp_ln1547_4_fu_174_p2;
wire   [15:0] trunc_ln717_4_fu_180_p4;
wire   [36:0] trunc_ln144_1_fu_130_p4;
wire   [0:0] icmp_ln1547_5_fu_198_p2;
wire   [15:0] trunc_ln717_5_fu_204_p4;
wire   [36:0] trunc_ln144_2_fu_140_p4;
wire   [0:0] icmp_ln1547_6_fu_222_p2;
wire   [15:0] trunc_ln717_6_fu_228_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_114;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

edge_cnn_linear_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_114)) begin
        if ((icmp_ln41_fu_99_p2 == 1'd0)) begin
            i_fu_74 <= i_7_fu_105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_74 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        select_ln51_4_reg_271 <= select_ln51_4_fu_190_p3;
        select_ln51_5_reg_276 <= select_ln51_5_fu_214_p3;
        select_ln51_6_reg_281 <= select_ln51_6_fu_238_p3;
        select_ln51_reg_266 <= select_ln51_fu_166_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_6 = 15'd0;
    end else begin
        ap_sig_allocacmp_i_6 = i_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_blk_n = layer2_out_empty_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_out_read = 1'b1;
    end else begin
        layer2_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer3_out_blk_n = layer3_out_full_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer3_out_write = 1'b1;
    end else begin
        layer3_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((layer3_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer2_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer3_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer2_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer3_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer2_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer2_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer3_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_114 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_7_fu_105_p2 = (ap_sig_allocacmp_i_6 + 15'd1);

assign icmp_ln1547_4_fu_174_p2 = (($signed(trunc_ln144_s_fu_120_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1547_5_fu_198_p2 = (($signed(trunc_ln144_1_fu_130_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1547_6_fu_222_p2 = (($signed(trunc_ln144_2_fu_140_p4) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1547_fu_150_p2 = (($signed(trunc_ln144_fu_116_p1) > $signed(37'd0)) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_99_p2 = ((ap_sig_allocacmp_i_6 == 15'd19602) ? 1'b1 : 1'b0);

assign layer3_out_din = {{{{select_ln51_6_reg_281}, {select_ln51_5_reg_276}}, {select_ln51_4_reg_271}}, {select_ln51_reg_266}};

assign select_ln51_4_fu_190_p3 = ((icmp_ln1547_4_fu_174_p2[0:0] == 1'b1) ? trunc_ln717_4_fu_180_p4 : 16'd0);

assign select_ln51_5_fu_214_p3 = ((icmp_ln1547_5_fu_198_p2[0:0] == 1'b1) ? trunc_ln717_5_fu_204_p4 : 16'd0);

assign select_ln51_6_fu_238_p3 = ((icmp_ln1547_6_fu_222_p2[0:0] == 1'b1) ? trunc_ln717_6_fu_228_p4 : 16'd0);

assign select_ln51_fu_166_p3 = ((icmp_ln1547_fu_150_p2[0:0] == 1'b1) ? trunc_ln2_fu_156_p4 : 16'd0);

assign start_out = real_start;

assign trunc_ln144_1_fu_130_p4 = {{layer2_out_dout[110:74]}};

assign trunc_ln144_2_fu_140_p4 = {{layer2_out_dout[147:111]}};

assign trunc_ln144_fu_116_p1 = layer2_out_dout[36:0];

assign trunc_ln144_s_fu_120_p4 = {{layer2_out_dout[73:37]}};

assign trunc_ln2_fu_156_p4 = {{layer2_out_dout[25:10]}};

assign trunc_ln717_4_fu_180_p4 = {{layer2_out_dout[62:47]}};

assign trunc_ln717_5_fu_204_p4 = {{layer2_out_dout[99:84]}};

assign trunc_ln717_6_fu_228_p4 = {{layer2_out_dout[136:121]}};

endmodule //edge_cnn_linear_relu_array_ap_fixed_37_17_5_3_0_4u_array_ap_fixed_16_6_5_3_0_4u_relu_config3_s
