// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module edge_cnn_linear_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_image_TDATA,
        input_image_TVALID,
        input_image_TREADY,
        layer7_out_din,
        layer7_out_full_n,
        layer7_out_write
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] input_image_TDATA;
input   input_image_TVALID;
output   input_image_TREADY;
output  [15:0] layer7_out_din;
input   layer7_out_full_n;
output   layer7_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg[15:0] layer7_out_din;
reg layer7_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer7_out_blk_n;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln59_fu_84_p2;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_done;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_idle;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_ready;
wire   [15:0] grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_layer7_out_din;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_layer7_out_write;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_done;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_idle;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_ready;
wire   [15:0] grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_layer7_out_din;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_layer7_out_write;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_done;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_idle;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_ready;
wire   [15:0] grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_layer7_out_din;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_layer7_out_write;
wire    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_input_image_TREADY;
reg    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start_reg;
reg    ap_block_state1_ignore_call4;
wire    ap_CS_fsm_state2;
reg    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start_reg;
reg    ap_block_state4_ignore_call1;
wire    ap_CS_fsm_state7;
reg    grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [6:0] i_fu_44;
wire   [6:0] add_ln59_fu_90_p2;
reg    ap_block_state4;
reg    ap_block_state1;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_input_image_U_apdone_blk;
wire   [15:0] input_image_TDATA_int_regslice;
wire    input_image_TVALID_int_regslice;
reg    input_image_TREADY_int_regslice;
wire    regslice_both_input_image_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start_reg = 1'b0;
#0 grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start_reg = 1'b0;
#0 grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start_reg = 1'b0;
end

edge_cnn_linear_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start),
    .ap_done(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_done),
    .ap_idle(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_idle),
    .ap_ready(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_ready),
    .layer7_out_din(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_layer7_out_din),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_layer7_out_write)
);

edge_cnn_linear_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start),
    .ap_done(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_done),
    .ap_idle(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_idle),
    .ap_ready(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_ready),
    .layer7_out_din(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_layer7_out_din),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_layer7_out_write)
);

edge_cnn_linear_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start),
    .ap_done(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_done),
    .ap_idle(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_idle),
    .ap_ready(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_ready),
    .layer7_out_din(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_layer7_out_din),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_layer7_out_write),
    .input_image_TVALID(input_image_TVALID_int_regslice),
    .input_image_TDATA(input_image_TDATA_int_regslice),
    .input_image_TREADY(grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_input_image_TREADY)
);

edge_cnn_linear_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_image_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_image_TDATA),
    .vld_in(input_image_TVALID),
    .ack_in(regslice_both_input_image_U_ack_in),
    .data_out(input_image_TDATA_int_regslice),
    .vld_out(input_image_TVALID_int_regslice),
    .ack_out(input_image_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_image_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_ready == 1'b1)) begin
            grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0)) & (icmp_ln59_fu_84_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_ready == 1'b1)) begin
            grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_ready == 1'b1)) begin
            grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_44 <= 7'd0;
    end else if ((~((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0)) & (icmp_ln59_fu_84_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        i_fu_44 <= add_ln59_fu_90_p2;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        input_image_TREADY_int_regslice = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_input_image_TREADY;
    end else begin
        input_image_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_84_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        layer7_out_blk_n = layer7_out_full_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0)) & (icmp_ln59_fu_84_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        layer7_out_din = 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        layer7_out_din = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_layer7_out_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer7_out_din = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_layer7_out_din;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        layer7_out_din = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_layer7_out_din;
    end else begin
        layer7_out_din = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_layer7_out_din;
    end
end

always @ (*) begin
    if ((~((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0)) & (icmp_ln59_fu_84_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        layer7_out_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        layer7_out_write = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_layer7_out_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer7_out_write = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_layer7_out_write;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        layer7_out_write = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_layer7_out_write;
    end else begin
        layer7_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if ((~((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0)) & (icmp_ln59_fu_84_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if ((~((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0)) & (icmp_ln59_fu_84_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln59_fu_90_p2 = (i_fu_44 + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call4 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_ignore_call1 = ((icmp_ln59_fu_84_p2 == 1'd0) & (layer7_out_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_CopyMain_fu_68_ap_start_reg;

assign grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadBottomWidth_fu_62_ap_start_reg;

assign grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start = grp_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_Pipeline_PadTopWidth_fu_56_ap_start_reg;

assign icmp_ln59_fu_84_p2 = ((i_fu_44 == 7'd121) ? 1'b1 : 1'b0);

assign input_image_TREADY = regslice_both_input_image_U_ack_in;

assign start_out = real_start;

endmodule //edge_cnn_linear_zeropad2d_cl_array_ap_fixed_16_6_5_3_0_1u_array_ap_fixed_16_6_5_3_0_1u_config7_s
