// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        layer4_out_TDATA,
        layer4_out_TVALID,
        layer4_out_TREADY
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
output  [7:0] layer4_out_TDATA;
output   layer4_out_TVALID;
input   layer4_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer4_out_TVALID;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
reg   [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3;
reg   [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5;
reg   [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2;
reg   [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
reg   [7:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
reg   [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7;
reg   [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6;
reg   [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1;
reg   [7:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a;
reg   [31:0] sX;
reg   [31:0] sY;
reg   [31:0] pY;
reg   [31:0] pX;
reg    layer4_out_TDATA_blk_n;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln284_reg_381;
reg   [0:0] and_ln284_1_reg_395;
wire   [0:0] icmp_ln284_fu_226_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] and_ln284_1_fu_283_p2;
wire   [0:0] icmp_ln303_fu_294_p2;
reg   [0:0] icmp_ln303_reg_399;
wire   [31:0] select_ln313_fu_358_p3;
wire   [0:0] icmp_ln307_fu_341_p2;
reg    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_done;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_idle;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_ready;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld;
wire   [7:0] call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o;
wire    call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_done;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_idle;
wire    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_ready;
wire   [7:0] grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_return;
reg   [31:0] storemerge_reg_111;
reg    ap_predicate_op25_write_state3;
reg    ap_block_state3;
reg    ap_block_state3_io;
reg    ap_predicate_op24_call_state3;
reg    ap_block_state3_on_subcall_done;
reg    grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg;
wire   [31:0] select_ln318_fu_311_p3;
wire    ap_CS_fsm_state4;
wire   [31:0] add_ln307_fu_336_p2;
wire   [31:0] add_ln303_fu_289_p2;
wire   [30:0] tmp_fu_245_p4;
wire   [30:0] tmp_3_fu_261_p4;
wire   [0:0] icmp_ln284_4_fu_255_p2;
wire   [0:0] icmp_ln284_5_fu_271_p2;
wire   [0:0] and_ln284_fu_277_p2;
wire   [0:0] grp_fu_217_p2;
wire   [31:0] add_ln318_fu_306_p2;
wire   [31:0] add_ln313_fu_353_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_condition_183;
reg    ap_condition_295;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 = 8'd0;
#0 p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3 = 8'd0;
#0 p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 = 8'd0;
#0 p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2 = 8'd0;
#0 p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 = 8'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 = 8'd0;
#0 p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7 = 8'd0;
#0 p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6 = 8'd0;
#0 p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1 = 8'd0;
#0 p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a = 8'd0;
#0 sX = 32'd0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 pX = 32'd0;
#0 grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg = 1'b0;
end

myproject_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start),
    .ap_done(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_done),
    .ap_idle(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_idle),
    .ap_ready(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_ready),
    .p_read(p_read),
    .p_read1(p_read1),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_i(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_i(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_i(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_i(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_i(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_i(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld(call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld)
);

myproject_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start),
    .ap_done(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_done),
    .ap_idle(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_idle),
    .ap_ready(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_ready),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1),
    .p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a(p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a),
    .ap_return(grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln284_fu_226_p2 == 1'd1) & (1'd1 == and_ln284_1_fu_283_p2) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_ready == 1'b1)) begin
            grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((icmp_ln303_fu_294_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln303_fu_294_p2 == 1'd0)) begin
            pX <= add_ln303_fu_289_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_295)) begin
        if ((icmp_ln307_fu_341_p2 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln307_fu_341_p2 == 1'd0)) begin
            pY <= add_ln307_fu_336_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((icmp_ln303_fu_294_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln303_fu_294_p2 == 1'd0)) begin
            sX <= select_ln318_fu_311_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_295)) begin
        if ((icmp_ln307_fu_341_p2 == 1'd1)) begin
            storemerge_reg_111 <= 32'd0;
        end else if ((icmp_ln307_fu_341_p2 == 1'd0)) begin
            storemerge_reg_111 <= select_ln313_fu_358_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln284_fu_226_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        and_ln284_1_reg_395 <= and_ln284_1_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln284_reg_381 <= icmp_ln284_fu_226_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln303_reg_399 <= icmp_ln303_fu_294_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4_ap_vld == 1'b1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5_ap_vld == 1'b1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o_ap_vld == 1'b1))) begin
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI8ap_fixedILi8ELi2EL9ap_q_mode5EL9a_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln303_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        sY <= storemerge_reg_111;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9 <= call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_9;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3_io) | ((layer4_out_TREADY == 1'b0) & (ap_predicate_op25_write_state3 == 1'b1)))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start = 1'b1;
    end else begin
        call_ln281_shift_line_buffer_array_ap_fixed_8_2_5_3_0_2u_config4_s_fu_122_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln284_1_reg_395) & (icmp_ln284_reg_381 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        layer4_out_TDATA_blk_n = layer4_out_TREADY;
    end else begin
        layer4_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3_io) | ((layer4_out_TREADY == 1'b0) & (ap_predicate_op25_write_state3 == 1'b1))) & (1'b1 == ap_CS_fsm_state3) & (ap_predicate_op25_write_state3 == 1'b1))) begin
        layer4_out_TVALID = 1'b1;
    end else begin
        layer4_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3_io) | ((layer4_out_TREADY == 1'b0) & (ap_predicate_op25_write_state3 == 1'b1))) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln303_fu_289_p2 = (pX + 32'd1);

assign add_ln307_fu_336_p2 = (pY + 32'd1);

assign add_ln313_fu_353_p2 = (sY + 32'd1);

assign add_ln318_fu_306_p2 = (sX + 32'd1);

assign and_ln284_1_fu_283_p2 = (grp_fu_217_p2 & and_ln284_fu_277_p2);

assign and_ln284_fu_277_p2 = (icmp_ln284_5_fu_271_p2 & icmp_ln284_4_fu_255_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state3 = ((layer4_out_TREADY == 1'b0) & (ap_predicate_op25_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state3_io = ((layer4_out_TREADY == 1'b0) & (ap_predicate_op25_write_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((ap_predicate_op24_call_state3 == 1'b1) & (grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_done == 1'b0));
end

always @ (*) begin
    ap_condition_183 = (~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3_io) | ((layer4_out_TREADY == 1'b0) & (ap_predicate_op25_write_state3 == 1'b1))) & (1'b1 == ap_CS_fsm_state3));
end

always @ (*) begin
    ap_condition_295 = (~((1'b1 == ap_block_state3_on_subcall_done) | (1'b1 == ap_block_state3_io) | ((layer4_out_TREADY == 1'b0) & (ap_predicate_op25_write_state3 == 1'b1))) & (icmp_ln303_fu_294_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3));
end

always @ (*) begin
    ap_predicate_op24_call_state3 = ((1'd1 == and_ln284_1_reg_395) & (icmp_ln284_reg_381 == 1'd1));
end

always @ (*) begin
    ap_predicate_op25_write_state3 = ((1'd1 == and_ln284_1_reg_395) & (icmp_ln284_reg_381 == 1'd1));
end

assign grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start = grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_start_reg;

assign grp_fu_217_p2 = ((sY == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln284_4_fu_255_p2 = (($signed(tmp_fu_245_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_5_fu_271_p2 = (($signed(tmp_3_fu_261_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln284_fu_226_p2 = ((sX == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln303_fu_294_p2 = ((add_ln303_fu_289_p2 == 32'd164) ? 1'b1 : 1'b0);

assign icmp_ln307_fu_341_p2 = ((add_ln307_fu_336_p2 == 32'd123) ? 1'b1 : 1'b0);

assign layer4_out_TDATA = grp_dense_resource_rf_leq_nin_ap_fixed_ap_fixed_8_2_5_3_0_config4_mult_s_fu_174_ap_return;

assign select_ln313_fu_358_p3 = ((grp_fu_217_p2[0:0] == 1'b1) ? 32'd2 : add_ln313_fu_353_p2);

assign select_ln318_fu_311_p3 = ((icmp_ln284_reg_381[0:0] == 1'b1) ? 32'd2 : add_ln318_fu_306_p2);

assign tmp_3_fu_261_p4 = {{pX[31:1]}};

assign tmp_fu_245_p4 = {{pY[31:1]}};

endmodule //myproject_compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_1u_config4_s
